// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var couch_utils;

  couch_utils = require('./couch_utils');

  module.exports = {
    auth_hack: function(req, res, next) {
      if (req.headers.cookie) {
        req.headers.cookie = req.headers.cookie.replace(/express_sess="(.*?)"/, 'express_sess=$1');
      }
      return next();
    },
    couch: function(req, res, next) {
      if (req.session.user) {
        req.couch = couch_utils.nano_user(req.session.user);
      }
      return next();
    }
  };

}).call(this);
