// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  module.exports = {
    lib: require('./_lib'),
    views: {
      by_type: {
        map: function(doc) {
          var team_data;
          log('by_type', require('lib'), require('lib/get_team_data'));
          team_data = require('lib/get_team_data')(doc._id);
          if (!team_data) {
            return;
          }
          return emit([team_data.team, team_data.typ, team_data.name], 1);
        }
      }
    },
    lists: {
      teams: {
        map: function(head, req) {
          var id_parts, out, row, _results;
          out = {};
          _results = [];
          while (row = getRow()) {
            id_parts = doc._id.split('_');
            if (id_parts[0] !== 't') {
              continue;
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        }
      },
      team: {
        map: function(head, req) {}
      }
    }
  };

}).call(this);
