// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var conf, couch_utils, get_all, gh_conf, gha, gha_url, iced, import_members, import_repos, import_team, parse_links, request, uuid, x, _, __iced_k, __iced_k_noop,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  iced = require('iced-runtime');
  __iced_k = __iced_k_noop = function() {};

  conf = require('../config');

  gh_conf = conf.RESOURCES.GH;

  request = require('request');

  parse_links = require('parse-links');

  couch_utils = require('../couch_utils');

  _ = require('underscore');

  uuid = require('node-uuid');

  gha_url = 'https://api.github.com';

  gha = request.defaults({
    auth: gh_conf.ADMIN_CREDENTIALS,
    json: true,
    headers: {
      'User-Agent': 'cfpb-kratos'
    }
  });

  get_all = function(client, url, callback) {
    var data, err, link_header, links, out, resp, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    out = [];
    (function(_this) {
      return (function(__iced_k) {
        var _results, _while;
        _results = [];
        _while = function(__iced_k) {
          var _break, _continue, _next;
          _break = function() {
            return __iced_k(_results);
          };
          _continue = function() {
            return iced.trampoline(function() {
              return _while(__iced_k);
            });
          };
          _next = function(__iced_next_arg) {
            _results.push(__iced_next_arg);
            return _continue();
          };
          if (!url) {
            return _break();
          } else {
            (function(__iced_k) {
              __iced_deferrals = new iced.Deferrals(__iced_k, {
                parent: ___iced_passed_deferral,
                filename: "/Users/greisend/programming/open-source-wizard/node/src/resources/gh.iced"
              });
              client.get(url, __iced_deferrals.defer({
                assign_fn: (function() {
                  return function() {
                    err = arguments[0];
                    resp = arguments[1];
                    return data = arguments[2];
                  };
                })(),
                lineno: 19
              }));
              __iced_deferrals._fulfill();
            })(function() {
              if (err) {
                return err;
              }
              out = out.concat(data);
              link_header = resp.headers.link;
              if (link_header != null) {
                links = parse_links(link_header);
              }
              return _next(url = (links != null ? links.next : void 0) || null);
            });
          }
        };
        _while(__iced_k);
      });
    })(this)((function(_this) {
      return function() {
        return callback(null, out);
      };
    })(this));
  };

  x = {};

  x.import_users = function(callback) {
    var db, err, i, member, members, url, users, uuids, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    url = gha_url + '/organizations/' + gh_conf.ORG_ID + '/members';
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/Users/greisend/programming/open-source-wizard/node/src/resources/gh.iced",
          funcname: "import_users"
        });
        get_all(gha, url, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              err = arguments[0];
              return members = arguments[1];
            };
          })(),
          lineno: 31
        }));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        users = [];
        (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/greisend/programming/open-source-wizard/node/src/resources/gh.iced",
            funcname: "import_users"
          });
          couch_utils.get_uuids(members.length, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                err = arguments[0];
                return uuids = arguments[1];
              };
            })(),
            lineno: 33
          }));
          __iced_deferrals._fulfill();
        })(function() {
          var _i, _len;
          for (i = _i = 0, _len = members.length; _i < _len; i = ++_i) {
            member = members[i];
            users.push({
              _id: "org.couchdb.user:" + uuids[i],
              type: "user",
              name: uuids[i],
              roles: [],
              username: member.login,
              resrcs: {
                gh: {
                  roles: {
                    user: false
                  },
                  data: {
                    login: member.login,
                    id: member.id
                  }
                }
              }
            });
          }
          db = couch_utils.nano.use('_users');
          return db.bulk({
            docs: users
          }, callback);
        });
      };
    })(this));
  };

  x.import_teams = function(db_name, admin_id, callback) {
    var db, err, i, name, perm, raw_team, raw_teams, resp, start_time, team, team_data, team_docs, team_name, teams, typ, url, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    start_time = +new Date();
    url = gha_url + '/organizations/' + gh_conf.ORG_ID + '/teams';
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/Users/greisend/programming/open-source-wizard/node/src/resources/gh.iced",
          funcname: "import_teams"
        });
        get_all(gha, url, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              err = arguments[0];
              return raw_teams = arguments[1];
            };
          })(),
          lineno: 58
        }));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        var _i, _len, _ref, _ref1;
        teams = {};
        for (_i = 0, _len = raw_teams.length; _i < _len; _i++) {
          raw_team = raw_teams[_i];
          if (_ref = raw_team.id, __indexOf.call(gh_conf.UNMANAGED_TEAMS, _ref) >= 0) {
            console.log('skipping', raw_team.id);
            continue;
          }
          _ref1 = raw_team.name.split(' '), name = _ref1[0], typ = _ref1[1], perm = _ref1[2];
          raw_team.perm = perm;
          raw_team.iname = name;
          if (typ !== 'team') {
            continue;
          }
          if (teams[name] == null) {
            teams[name] = {};
          }
          teams[name][perm] = raw_team;
        }
        team_data = [];
        (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/greisend/programming/open-source-wizard/node/src/resources/gh.iced",
            funcname: "import_teams"
          });
          i = 0;
          for (team_name in teams) {
            team = teams[team_name];
            import_team(team, admin_id, __iced_deferrals.defer({
              assign_fn: (function(__slot_1, __slot_2) {
                return function() {
                  err = arguments[0];
                  return __slot_1[__slot_2] = arguments[1];
                };
              })(team_data, i),
              lineno: 76
            }));
            i++;
          }
          __iced_deferrals._fulfill();
        })(function() {
          team_docs = {
            docs: _.flatten(team_data, true)
          };
          db = couch_utils.nano.use('org_' + db_name);
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "/Users/greisend/programming/open-source-wizard/node/src/resources/gh.iced",
              funcname: "import_teams"
            });
            couch_utils.ensure_db(db, 'bulk', team_docs, __iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  err = arguments[0];
                  return resp = arguments[1];
                };
              })(),
              lineno: 80
            }));
            __iced_deferrals._fulfill();
          })(function() {
            console.log('total time:', +new Date() - start_time);
            return callback();
          });
        });
      };
    })(this));
  };

  import_team = function(teams, admin_id, callback) {
    var err, i, role_doc, rsrc_doc, team_doc, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    team_doc = {
      _id: 'team_' + teams['admin'].iname,
      name: teams['admin'].iname
    };
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/Users/greisend/programming/open-source-wizard/node/src/resources/gh.iced"
        });
        import_repos(teams['admin'], admin_id, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              err = arguments[0];
              return rsrc_doc = arguments[1];
            };
          })(),
          lineno: 90
        }));
        i = 0;
        import_members(teams, admin_id, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              err = arguments[0];
              return role_doc = arguments[1];
            };
          })(),
          lineno: 92
        }));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        return callback(null, [team_doc, role_doc, rsrc_doc]);
      };
    })(this));
  };

  import_members = function(teams, admin_id, callback) {
    var err, i, member_gh_ids, members, now, role_doc, team, team_name, url, user, user_rows, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    now = +new Date();
    role_doc = {
      _id: 'role_member_' + teams['admin'].iname,
      members: [],
      audit: [
        {
          u: admin_id,
          dt: now,
          a: '+',
          id: uuid.v4()
        }
      ],
      enforce: [],
      rsrcs_data: {
        gh: _.object(_.map(teams, function(item) {
          return [item.perm, item.id];
        }))
      }
    };
    members = [];
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/Users/greisend/programming/open-source-wizard/node/src/resources/gh.iced"
        });
        i = 0;
        for (team_name in teams) {
          team = teams[team_name];
          url = team.url + '/members';
          get_all(gha, url, __iced_deferrals.defer({
            assign_fn: (function(__slot_1, __slot_2) {
              return function() {
                err = arguments[0];
                return __slot_1[__slot_2] = arguments[1];
              };
            })(members, i),
            lineno: 112
          }));
          i++;
        }
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        members = _.flatten(members, true);
        members = _.map(members, function(item) {
          return item.id;
        });
        members = _.uniq(members);
        member_gh_ids = _.map(members, function(item) {
          return ['gh', item];
        });
        (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/greisend/programming/open-source-wizard/node/src/resources/gh.iced"
          });
          couch_utils.nano.use('_users').view('base', 'by_resource_id', {
            keys: member_gh_ids
          }, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                err = arguments[0];
                return user_rows = arguments[1];
              };
            })(),
            lineno: 118
          }));
          __iced_deferrals._fulfill();
        })(function() {
          var _i, _len, _ref;
          _ref = user_rows.rows;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            user = _ref[_i];
            role_doc.members.push(user.value);
            role_doc.audit.push({
              u: admin_id,
              dt: now,
              a: 'c',
              r: user.value,
              id: uuid.v4()
            });
          }
          return callback(null, role_doc);
        });
      };
    })(this));
  };

  import_repos = function(team, admin_id, callback) {
    var err, now, repo, repo_record, repos, resource_doc, url, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    now = +new Date();
    resource_doc = {
      _id: 'rsrc_gh_' + team.iname,
      assets: [],
      audit: [
        {
          u: admin_id,
          dt: now,
          a: '+',
          id: uuid.v4()
        }
      ],
      enforce: []
    };
    url = team.url + '/repos';
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/Users/greisend/programming/open-source-wizard/node/src/resources/gh.iced"
        });
        get_all(gha, url, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              err = arguments[0];
              return repos = arguments[1];
            };
          })(),
          lineno: 135
        }));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        var _i, _len;
        for (_i = 0, _len = repos.length; _i < _len; _i++) {
          repo = repos[_i];
          repo_record = {
            id: repo.id,
            name: repo.name,
            full_name: repo.full_name
          };
          resource_doc.assets.push(repo_record);
          resource_doc.audit.push({
            u: admin_id,
            dt: now,
            a: 'c',
            r: repo_record,
            id: uuid.v4()
          });
        }
        return callback(null, resource_doc);
      };
    })(this));
  };

  module.exports = x;


  /*
  gh = require('./gh')
  gh.import_teams('devdesign', 'c0301d9be96094b552835c014f01cf07', function(err, resp) {console.log(err, resp)})
  gh.import_all(function(err, resp) {console.log(err, resp)})
   */

}).call(this);
