// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var roles;

  roles = {};

  roles.add_member = function(req, resp) {};

  roles.remove_member = function(req, resp) {};

  module.exports = roles;

}).call(this);
