// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var couch_utils, request, teams;

  couch_utils = require('../couch_utils');

  request = require('request');

  teams = {};

  teams.update_team = function(req, resp) {};

  teams.get_team = function(req, resp) {
    var org, team;
    org = 'org_' + req.params.org_id;
    team = 'team_' + req.params.team_id;
    return couch_utils.nano_admin.use(org).get(team).pipe(resp);
  };

  teams.get_teams = function(req, resp) {
    var org;
    org = 'org_' + req.params.org_id;
    return couch_utils.nano_admin.use(org).viewWithList('base', 'by_type', 'get_docs', {
      include_docs: true
    }).pipe(resp);
  };

  teams.add_remove_member_asset = function(action_type) {
    return function(req, resp) {
      var action, db, org, team;
      org = 'org_' + req.params.org_id;
      team = 'team_' + req.params.team_id;
      db = req.couch.use(org);
      action = {
        action: action_type,
        key: req.params.key,
        value: req.params.value
      };
      return db.atomic('base', 'do_action', team, action).pipe(resp);
    };
  };

  module.exports = teams;

}).call(this);
