// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var couch_utils, request, teams;

  couch_utils = require('../couch_utils');

  request = require('request');

  teams = {};

  teams.update_team = function(req, resp) {};

  teams.get_team = function(req, resp) {};

  teams.get_teams = function(req, resp, org) {
    req.session.hello = 'world';
    return couch_utils.nano.request({
      db: 'org_devdesign',
      path: '/_design/base/_rewrite/teams'
    }).pipe(resp);
  };

  module.exports = teams;

}).call(this);
