// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var h;

  h = {};

  h.sanitize_user = function(user) {
    delete user.password_scheme;
    delete user.iterations;
    delete user.derived_key;
    delete user.salt;
    return user;
  };

  module.exports = h;

}).call(this);
