// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  (function(perms) {
    return perms.kratos = {
      add_team: function(user) {
        var _ref, _ref1;
        return ((_ref = user.resrcs.kratos) != null ? (_ref1 = _ref.roles) != null ? _ref1.admin : void 0 : void 0) || false;
      },
      remove_team: function(user) {
        var _ref, _ref1;
        return ((_ref = user.resrcs.kratos) != null ? (_ref1 = _ref.roles) != null ? _ref1.admin : void 0 : void 0) || false;
      }
    };
  });

}).call(this);
